// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZK43poN0cFmdiIYFRzSvywOxEqaIIY8E',
    appId: '1:333633367376:web:86362804739eb2039a5055',
    messagingSenderId: '333633367376',
    projectId: 'pentingpayustore',
    authDomain: 'pentingpayustore.firebaseapp.com',
    storageBucket: 'pentingpayustore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8aXIhihdyCkqVQ_nFOAxSSJcm3UF_hPk',
    appId: '1:333633367376:ios:dcf36259fdf3c8bc9a5055',
    messagingSenderId: '333633367376',
    projectId: 'pentingpayustore',
    storageBucket: 'pentingpayustore.firebasestorage.app',
    iosBundleId: 'com.example.paymentGateawayApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8aXIhihdyCkqVQ_nFOAxSSJcm3UF_hPk',
    appId: '1:333633367376:ios:dcf36259fdf3c8bc9a5055',
    messagingSenderId: '333633367376',
    projectId: 'pentingpayustore',
    storageBucket: 'pentingpayustore.firebasestorage.app',
    iosBundleId: 'com.example.paymentGateawayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZK43poN0cFmdiIYFRzSvywOxEqaIIY8E',
    appId: '1:333633367376:web:f0aa4633c58d16db9a5055',
    messagingSenderId: '333633367376',
    projectId: 'pentingpayustore',
    authDomain: 'pentingpayustore.firebaseapp.com',
    storageBucket: 'pentingpayustore.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtz6-KAUqeAkFBrhOtRhqRPBDjCS6iTtY',
    appId: '1:333633367376:android:868c81976a6834b29a5055',
    messagingSenderId: '333633367376',
    projectId: 'pentingpayustore',
    storageBucket: 'pentingpayustore.firebasestorage.app',
  );

}