// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDABT0Ny5kNkzg9h928IhUeTl2UDMVYDBI',
    appId: '1:530435381631:web:d7a86f00302b6ec38c624a',
    messagingSenderId: '530435381631',
    projectId: 'project-flutter-notification',
    authDomain: 'project-flutter-notification.firebaseapp.com',
    storageBucket: 'project-flutter-notification.firebasestorage.app',
    measurementId: 'G-DB7LDW9WYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQGcBDNZlHvWOzHKvQvjCjLG9y9TA5nbU',
    appId: '1:530435381631:android:46f0dbed6afb8bb48c624a',
    messagingSenderId: '530435381631',
    projectId: 'project-flutter-notification',
    storageBucket: 'project-flutter-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9XjCvlYDErRpF8I8178PWuXQJ-tjWRWY',
    appId: '1:530435381631:ios:6ab6f06e4bcdeda88c624a',
    messagingSenderId: '530435381631',
    projectId: 'project-flutter-notification',
    storageBucket: 'project-flutter-notification.firebasestorage.app',
    androidClientId: '530435381631-n8rj6t68ead5pdlru6rllosaacp1bh0k.apps.googleusercontent.com',
    iosClientId: '530435381631-f9hrrti9koks5vijhhnj9fdkdi5tsn02.apps.googleusercontent.com',
    iosBundleId: 'com.example.gandumGoreng',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9XjCvlYDErRpF8I8178PWuXQJ-tjWRWY',
    appId: '1:530435381631:ios:6ab6f06e4bcdeda88c624a',
    messagingSenderId: '530435381631',
    projectId: 'project-flutter-notification',
    storageBucket: 'project-flutter-notification.firebasestorage.app',
    androidClientId: '530435381631-n8rj6t68ead5pdlru6rllosaacp1bh0k.apps.googleusercontent.com',
    iosClientId: '530435381631-f9hrrti9koks5vijhhnj9fdkdi5tsn02.apps.googleusercontent.com',
    iosBundleId: 'com.example.gandumGoreng',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDABT0Ny5kNkzg9h928IhUeTl2UDMVYDBI',
    appId: '1:530435381631:web:f1a7cb8bba0ed7df8c624a',
    messagingSenderId: '530435381631',
    projectId: 'project-flutter-notification',
    authDomain: 'project-flutter-notification.firebaseapp.com',
    storageBucket: 'project-flutter-notification.firebasestorage.app',
    measurementId: 'G-EL0WVSG8F2',
  );
}
